aplicaciones/admon/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    #usuarios
    path('usuario/list/',UserListView.as_view(), name='user_list'),
    path('usuario/new/',UserCreateView.as_view(), name='user_new'),
    path('usuario/edit/<int:pk>',UserEditView.as_view(), name='user_edit'),
    path('usuario/del/<int:pk>',UsuarioDeleteView.as_view(), name='user_del'),
    path('usuario/ver/<int:pk>',UserDetalleView.as_view(), name='user_ver'),   
    path('profile/', UserPerfilView.as_view(), name='user_profile'),
    
    path('usuario/change/password/', PasswordChangeView.as_view(), name='user_change_pass'),
]

universidad/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from universidad import settings



urlpatterns = [
    path('',include(('aplicaciones.home.urls','home'), namespace='home')),
    path('config/',include(('aplicaciones.config.urls','config'), namespace='config')),   
    path('administrar/',include(('aplicaciones.admon.urls','admon'), namespace='admon')),   
    path('geografico/', include(('aplicaciones.geografico.urls', 'geografico'), namespace='geografico')),
    path('catedratico/', include(('aplicaciones.catedratico.urls', 'catedratico'), namespace='catedratico')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplicaciones/admon/models.py
from django.db import models
from django.db.models.fields import BooleanField, DateField, EmailField
from django.utils import timezone
from urllib.parse import urlencode as original_urlencode
#from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from universidad.settings import MEDIA_URL, STATIC_URL
#from crum import get_current_user
from .mannager import UsuarioManager
from aplicaciones.config.models import AuditModel
from aplicaciones.config.choices import GENDER_CHOICES

# Create your models here.
class Usuario(AuditModel, AbstractUser, PermissionsMixin):    
    avatar = models.ImageField(upload_to='user/%Y/%m/%d/', verbose_name="Imagen",blank=True)
    token = models.UUIDField(primary_key=False, editable=False, verbose_name="Token", null=True, blank=True)    
    telefono = models.CharField(max_length=10, verbose_name="Telefono")
    genero = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name="Genero")
    email =models.EmailField(verbose_name="Correo Electrónico")
    first_name = models.CharField(verbose_name="Nombres", max_length=100)
    last_name = models.CharField(verbose_name="Apellidos", max_length=100)
    #
    is_staff = models.BooleanField(default=False, verbose_name="Tiene Acceso a administracion")
    is_active = models.BooleanField(default=True, verbose_name="Esta Activo")
    is_superuser =models.BooleanField(default=False, verbose_name="Es usuario Administrador")

   #especificamos el atributo para hacerlogin en la app
    USERNAME_FIELD = 'username'
    #esto hace que pida el campo a requerir en la creación.
    REQUIRED_FIELDS = ['first_name', 'last_name', 'email', 'password', 'genero', 'telefono']

    #funcion para que me retorne el username, nombre corto
    def get_short_name(self):
        return self.username       

    def get_avatar(self):
        if self.avatar:
            return '{}{}'.format(MEDIA_URL, self.avatar)
        return '{}{}'.format(STATIC_URL, 'dist/img/empty.png')

    objects = UsuarioManager()
    
    def get_absolute_url(self):        
        return "/users/%s" % original_urlencode(self.username)

    #funcion para que me retorne el nombre y el apellido completo.
    def get_full_name (self):
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()    
    
    class Meta:
        verbose_name = ('Usuario')
        verbose_name_plural = ('Usuarios')

aplicaciones/admon/forms.py
from django import forms
from django.forms import ModelForm
from .models import Usuario


class UserForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['autofocus'] = True

    class Meta:
        model = Usuario
        fields = ['avatar', 'username', 'password', 'first_name', 'last_name', 'telefono', 'genero', 'email',
                  'is_active', 'is_staff', 'is_superuser']

        widgets = {
            'username': forms.TextInput(
                attrs={'placeholder': 'Usuario', 'class': 'input-group-field', 'help_text': '.', }),
            'password': forms.PasswordInput(render_value=True, attrs={'placeholder': 'Ingrese su password',
                                                                      'class': 'input-group-field', }),
            'first_name': forms.TextInput(
                attrs={'placeholder': 'Ingrese su nombre(s)', 'class': 'input-group-field', }),
            'last_name': forms.TextInput(
                attrs={'placeholder': 'Ingres sus apellido(s)', 'class': 'input-group-field', }),
            'telefono': forms.TextInput(
                attrs={'placeholder': 'Ingrese número teléfono', 'class': 'input-group-field', }),
            # 'habilidad':forms.SelectMultiple (attrs={'placeholder': 'Seleccione sus Habilidades'}),
            'genero': forms.Select(attrs={'placeholder': 'Seleccione su genero', 'class': 'input-group-field', }),
            'email': forms.EmailInput(
                attrs={'placeholder': 'Ingrese su correo electronico', 'class': 'input-group-field', }),
            'is_active': forms.CheckboxInput(attrs={}),
            'is_staff': forms.CheckboxInput(attrs={}),
            'is_superuser': forms.CheckboxInput(attrs={}),
            

        }
        exclude = ['groups', 'user_permissions', 'last_login', 'date_joined', 'created_by', 'modified_by']

    def save(self, commit=True):
        form = super()
        if form.is_valid():
            pwd = self.cleaned_data['password']
            u = form.save(commit=False)
            if u.pk is None:
                u.set_password(pwd)
            else:
                user = Usuario.objects.get(pk=u.pk)
                if user.password != pwd:
                    u.set_password(pwd)
            u.save()            
        return form



class UserProfileForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['autofocus'] = True

    class Meta:
        model = Usuario
        fields = ['avatar', 'username', 'password', 'first_name', 'last_name', 'telefono', 'email']
        widgets = {
            'username': forms.TextInput(
                attrs={'placeholder': 'Usuario', 'class': 'input-group-field', 'help_text': '.', }),
            'password': forms.PasswordInput(render_value=True, attrs={'placeholder': 'Ingrese su password',
                                                                      'class': 'input-group-field', }),
            'first_name': forms.TextInput(
                attrs={'placeholder': 'Ingrese su nombre(s)', 'class': 'input-group-field', }),
            'last_name': forms.TextInput(
                attrs={'placeholder': 'Ingres sus apellido(s)', 'class': 'input-group-field', }),
            'telefono': forms.TextInput(
                attrs={'placeholder': 'Ingrese número teléfono', 'class': 'input-group-field', }),
            # 'habilidad':forms.SelectMultiple (attrs={'placeholder': 'Seleccione sus Habilidades'}),        
            'email': forms.EmailInput(
                attrs={'placeholder': 'Ingrese su correo electronico', 'class': 'input-group-field', }),
        }

        exclude = ['genero', 'user_permissions', 'last_login', 'date_joined', 'is_superuser', 'is_active', 'is_staff',
                   'groups', 'created_by', 'modified_by']

    def save(self, commit=True):
        form = super()
        if form.is_valid():
            pwd = self.cleaned_data['password']
            u = form.save(commit=False)
            if u.pk is None:
                u.set_password(pwd)
            else:
                user = Usuario.objects.get(pk=u.pk)
                if user.password != pwd:
                    u.set_password(pwd)
            u.save()
        return form

aplicaciones/admon/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.views.decorators.debug import sensitive_post_parameters
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, View, FormView
from django.urls import reverse_lazy
from django.contrib import messages

from django.contrib.messages.views import SuccessMessageMixin

from aplicaciones.config.views import SinPrivilegios, ValidatePermissionRequiredMixin
from .models import Usuario
from .forms import UserForm, UserProfileForm

class UserListView(SuccessMessageMixin, SinPrivilegios, ListView):
    permission_required = 'view_usuario'
    model = Usuario
    template_name = "usuarios/listar.html"
    context_object_name = "obj"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Datos del usuario'
        context['create_url'] = reverse_lazy('admon:user_new')
        context['list_url'] = reverse_lazy('admon:user_list')
        context['entity'] = 'Usuario'
        return context


class UserCreateView(SinPrivilegios, SuccessMessageMixin, CreateView):
    permission_required = 'add_usuario'
    model = Usuario
    form_class = UserForm
    template_name = 'usuarios/add.html'
    success_url = reverse_lazy('admon:user_list')
    context_object_name = "obj"
    success_message = "Registro "" '%(username)s '"" Creado Satisfactoriamente"
    error_message = "Error al Intentar crear el Usuario, verifique los datos"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, self.error_message)
        return super().form_invalid(form)

    def form_submit(self, request):
        if request.method == 'POST':
            form = UserForm(request.POST)
            if form.is_valid():
                form.save()
            else:
                messages.error(request, self.error_message)

            return HttpResponseRedirect(self.success_url)
        return self.success_url

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Creación de un Usuario'
        context['entity'] = 'Usuarios'
        context['list_url'] = self.success_url

        return context


class UserEditView(SinPrivilegios, SuccessMessageMixin, UpdateView):
    permission_required = 'change_usuario'
    model = Usuario
    form_class = UserForm
    template_name = 'usuarios/add.html'
    success_url = reverse_lazy('admon:user_list')
    context_object_name = "obj"
    success_message = "Registro "" ' %(username)s ' "" Actualizado Satisfactoriamente"
    error_message = "Error al actualizar el registro "" '%(username)s' "", verifique los Campos."

    def form_valid(self, form):
        form.instance.modified_by = self.request.user
        return super().form_valid(form)

    def form_submit(self, request):
        if request.method == 'POST':
            form = UserForm(request.POST)
            if form.is_valid():
                messages.success(self.request, self.success_message)
                form.save()
            else:
                messages.error(self.request, self.error_message)
            return HttpResponseRedirect(self.success_url)
        return self.success_url

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Actualizar Datos'
        context['entity'] = 'Usuario'
        context['list_url'] = self.success_url
        return context


class UsuarioDeleteView(SinPrivilegios, SuccessMessageMixin, DeleteView):
    permission_required = "delete_usuario"
    model = Usuario
    template_name = 'usuarios/del.html'
    context_object_name = 'obj'
    success_url = reverse_lazy("admon:user_list")
    success_message = "Registro "" '%(username)s' "" Eliminado Satisfactoriamente"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminar Usuario'
        context['entity'] = 'Usuario'
        context['list_url'] = self.success_url
        return context


class UserDetalleView(SuccessMessageMixin, DetailView):
    model = Usuario
    template_name = 'usuarios/detalle.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Detalle de '
        context['entity'] = 'Usuario'
        context['volver'] = reverse_lazy('admon:user_list')
        context['encabezado'] = 'Detalle de usuario'
        # context['list_url'] = self.success_url
        return context


class UserChangeGroup(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            request.session['group'] = Group.objects.get(pk=self.kwargs['pk'])
        except:
            pass
        return HttpResponseRedirect(reverse_lazy('bases:home'))


class UserPerfilView(SinPrivilegios, SuccessMessageMixin, UpdateView):
    model = Usuario
    form_class = UserProfileForm
    template_name = 'usuarios/perfil.html'
    success_url = reverse_lazy('admon:user_list')
    context_object_name = "obj"
    permission_required = 'change_usuario'
    success_message = "Registro "" '%(username)s' "" Actualizado Satisfactoriamente"
    error_meesage = "Error al actualizar el registro "" '%(username)s' "" verifique los Campos ."

    url_redirect = success_url

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        form.instance.u_m = self.request.user
        return super().form_valid(form)

    def form_submit(self, request):
        if request.method == 'POST':
            form = UserProfileForm(request.POST)
            if form.is_valid():
                form.save()
            else:
                messages.error(self.request, self.error_message)
            return HttpResponseRedirect(self.url_redirect)
        return self.url_redirect

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Actualizar Perfil'
        context['entity'] = '/Usuario/Perfil'
        context['list_url'] = self.success_url
        return context


class PasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, FormView):
    model = Usuario
    form_class = PasswordChangeForm
    success_url = reverse_lazy('bases:login')
    template_name = 'usuarios/change_pass.html'
    success_message = 'Datos Actualizados Satisfactoriamente'
    error_message = 'error'

    def get_form_kwargs(self):
        kwargs = super(PasswordChangeView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        if self.request.method == 'POST':
            kwargs['data'] = self.request.POST
        return kwargs

    def form_invalid(self, form):
        messages.error(self.request, self.error_message)
        return super(PasswordChangeView, self).form_invalid(form)

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Datos almacenados satisfactoriamente')
        update_session_auth_hash(self.request, form.user)
        return super(PasswordChangeView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edición de Password'
        context['entity'] = 'Password'
        context['list_url'] = self.success_url
        return context

aplicaciones/admon/templates/usuarios/add.html
{% extends 'esquema/body.html' %}
{% load widget_tweaks %}

{% block content %}
<form method="POST" class="form-horizontal" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card mx-auto" style="max-width: 650px;">
        <div class="row no-gutters" style="align-content: flex-start;">
            <div class="col bg-info" style="max-width: 10px;">
            </div>
            <div class="col">
                <div class="card-header bg-info">
                    <h4>{{ title }}</h4>                
                </div>
                <div class="card-body">
                   {% block texto %}
                   
                   {% endblock %}

                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label >{{ field.label }}:</label>
                        {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                    </div>
                    {% endfor %}                   
                </div>
                <div class="card-footer text-center">
                    <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                    <a href="{{list_url}}" class="btn btn-success"> <span class="fa fa-undo"> </span> Cancelar</a>
                </div>
            </div>
        </div>
    </div>

</form>

{% endblock %}

{% block js_page %}
<script>
  {% if form.errors %}
        {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors %}
                    mensaje('{{ error|escape }}','red');
                {% endfor %}
            {% endif %}
        {% endfor %}

      {% if form.non_field_errors%}
          {% for error in form.non_field_errors %}
            mensaje('{{ error|escape }}','green');
          {% endfor %}
      {% endif %}
  {% endif %}
</script>

{% endblock %}

aplicaciones/admon/templates/usuarios/change_pass.html
{% extends 'cruds/form.html' %}
{% block texto %}
    <div class="containter">
        <div class="row">
            <div class="col bg-info text-white list-group-unbordered ">
                <p>Su contraseña no puede asemejarse tanto a su otra información
                    personal.</p>
                <p>Su contraseña debe contener al menos 8 caracteres.</p>
                <p>Su contraseña no puede ser una clave utilizada comúnmente.</p>
                <p>Inicie con una Letra y luego puede conbinar numeros.</p>
            </div>
        </div>
    </div>

{% endblock %}

aplicaciones/admon/templates/usuarios/del.html
{% extends 'esquema/body.html' %}

{% block content %}
<form method="POST" class="form-inline">
  {% csrf_token %}
  <div class="card mx-auto" style="max-width: 750px;">
    <div class="row no-gutters">
      <div class="col">
        <div class="card-header bg-info">
          <h3 class="card-title">
            <h4>{{ title }}</h4>
        </div>
        <div class="card-body">
          <div class="text-xs font-weight-bold text-danger text-uppercase mb-2"> <B style="font-size: 12pt;"> ¿Desea
            Eliminar el Registro </b> <b style="font-size: 12pt; color: orange;">{{obj.id}} {{ obj.get_short_name }} </b>
            <i class="far fa-question-circle fa-2x text-info"></i>
          </div>
        </div>

        <div class="card-footer text-center">
          <button type="submit" class="btn btn-danger">Si, Eliminar <i class="far fa-question-circle"></i></button>
          <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success">No, Cancelar <span class="fa fa-undo"></span></a>
        </div>

      </div>
    </div>
  </div>

</form>
{% endblock %}
{% block js_page %}
{% endblock %}

aplicaciones/admon/templates/usuarios/detalle.html
{% extends 'cruds/detalle.html' %}
{% load widget_tweaks %}
{% load static  %}
{% block detalle %}
    
<div class="row">
    <div class="col-md-12">
        <div class="col-md-12">
          
            <img src="{{object.get_avatar }}" width="15%" alt=""> 
           
        </div>
    </div>
</div>

<div class="row">
    <table id="table2" class="table table-bordered table-striped table-hover">    
        <tbody>
            <tr>
                <td class="bg-gray"> <strong>Id: </strong> </td>
                <td> {{ object.id }} </td>
                <td class="bg-gray"><strong>Username: </strong></td>
                <td> {{ object.username }} </td>
            </tr>
            <tr>
                <td class="bg-gray"> <strong>Nombre: </strong> </td>
                <td> {{ object.first_name }} </td>
                <td class="bg-gray"><strong>Apellido: </strong></td>
                <td> {{ object.last_name }} </td>
            </tr>
            <tr>
                <td class="bg-gray"> <strong>Genero: </strong> </td>
                <td> {{ object.get_genero_display }} </td>
                <td class="bg-gray"><strong>Telefono: </strong></td>
                <td> {{ object.telefono }} </td>
            </tr>
            <tr>                
                <td class="bg-gray"><Strong>Email:</Strong>:</td>
                <td>{{object.email}} </td>
                <td class="bg-gray"><Strong>Activo:</Strong>:</td>
                <td>{{object.is_active|yesno:"SI,No" }} </td>
            </tr>
            <tr>                
                <td class="bg-gray"><Strong>Tiene Acceso a Administracion:</Strong></td>
                <td>{{object.is_staff|yesno:"SI,No"}} </td> 
                <td class="bg-gray align-middle"><Strong>Es Super Usuario:</Strong>:</td>
                <td class="align-middle">{{object.is_superuser|yesno:"SI,No"}} </td>   
            </tr>    
            <tr>            
                <td class="bg-gray align-middle"> <strong> Pertenece a los grupos: </strong>  </td>
                <td class="align-middle">
                    <ul class="vertical menu">
                        {% for g in usuario.groups.all %}
                            <li>
                                {{ g }}
                            </li>                    
                        {% endfor %}
                    </ul>    
                </td>
                <td class="bg-gray align-middle"><Strong>Ultimo Acceso:</Strong>:</td>
                <td class="align-middle">{{object.last_login|date:"d/m/Y H:i:s" }} </td>
            </tr>
            <tr>
                <td class="bg-gray align-middle"><Strong>Creado por:</Strong></td>
                <td class="align-middle">{{object.u_c.username}} </td>
                <td class="bg-gray align-middle"><Strong>Fecha de Alta:</Strong></td>
                <td class="align-middle">{{object.f_c|date:"d/m/Y H:i:s"}} </td>    
            </tr>
            <tr>
                <td class="bg-gray align-middle"><Strong>Ultima Actualizacion por:</Strong>:</td>
                <td class="align-middle">{{object.u_m.username }} </td>
                <td class="bg-gray align-middle"><Strong>Modificado el:</Strong>:</td>
                <td class="align-middle">{{object.f_m|date:"d/m/Y H:i:s" }} </td>               
            </tr>
           
        </tbody>    
    </table>
   
   
</div>   
{% endblock detalle %}

{% block js_page %}
<script>
    $(function () {
       $("#table2").DataTable({
         "responsive": true, "lengthChange": false, "autoWidth": false,
         "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
       }).buttons().container().appendTo('#table_wrapper .col-md-6:eq(0)');
    });
</script>
{% endblock %}

aplicaciones/admon/templates/usuarios/listar.html
{% extends 'cruds/list.html' %}

{% block table_head %}
    <th align="center">ID</th>
    <th align="center">Usuario</th>
    <th align="center">Nombre</th>
    <th align="center">Fecha Creación</th>
    <th align="center">Fecha Actualización</th>
    <th align="center">Estado</th>
    <th align="center">Acciones</th>
{% endblock table_head %}

{% block table_body %}
    <td align="center">{{ e.id }}</td>
    <td>{{ e.username }}</td>
    <td>{{ e.get_full_name }}</td>
    <td align="center">{{ e.created_date|date:"d/m/Y" }}</td>
    <td align="center">{{ e.modified_date|date:"d/m/Y" }}</td>
    <td align="center">{{ e.is_active|yesno:"Activo,Inactivo" }}</td>
    <td  align="center">
        <a href="{% url 'admon:user_ver' e.id %}" class="btn btn-warning btn-circle btn-xs" role="button"><i
            class="far fa-eye"> </i></a>
        <a href="{% url 'admon:user_edit' e.id %}" class="btn btn-warning btn-circle btn-xs" role="button"><i
            class="far fa-edit"> </i></a>        
    </td>
{% endblock table_body %}

aplicaciones/admon/templates/usuarios/perfil.html
{% extends 'cruds/form.html' %}

{% block formulario_contenido %}

<table class="table-sm-secondary table-bordered table-striped" style="margin-inline: 0px; align-content:space-between;">

   {{ form.as_table }}

</table>

{% endblock formulario_contenido %}