aplicaciones/geografico/urls.py
from django.urls import path
from .views import *

urlpatterns = [    
    path('pais/list/', PaisListView.as_view(), name='pais_list'),
    path('pais/alta/', PaisNew.as_view(), name='pais_new'),
    path('pais/update/<int:pk>', PaisEdit.as_view(), name='pais_edit'),
    path('pais/inactivar/<int:id>', pais_inactivar, name='pais_inactivar'),

    path('depto/list/', DepartamentoListView.as_view(), name='depto_list'),
    path('depto/alta/', DepartamentoNew.as_view(), name='depto_new'),
    path('depto/update/<int:pk>', DepartamentoEdit.as_view(), name='depto_edit'),
    path('depto/inactivar/<int:id>', depto_inactivar, name='depto_inactivar'),

    path('ciudad/list/', CiudadListView.as_view(), name='ciudad_list'),
    path('ciudad/alta/', CiudadNew.as_view(), name='ciudad_new'),
    path('ciudad/update/<int:pk>', CiudadEdit.as_view(), name='ciudad_edit'),
    path('ciudad/inactivar/<int:id>', ciudad_inactivar, name='ciudad_inactivar'),

    path('conocimiento/list/', ConocimientoListView.as_view(), name='cono_list'),
    path('conocimiento/alta/', ConocimientoNew.as_view(), name='cono_new'),
    path('conocimiento/update/<int:pk>', ConocimientoEdit.as_view(), name='cono_edit'),
    path('conocimiento/inactivar/<int:id>', cono_inactivar, name='cono_inactivar'),

    path('formacion/list/', FormacionListView.as_view(), name='form_list'),
    path('formacion/alta/', FormacionNew.as_view(), name='form_new'),
    path('formacion/update/<int:pk>', FormacionEdit.as_view(), name='form_edit'),
    path('formacion/inactivar/<int:id>', form_inactivar, name='form_inactivar'),

]

universidad/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from universidad import settings



urlpatterns = [
    path('',include(('aplicaciones.home.urls','home'), namespace='home')),
    path('config/',include(('aplicaciones.config.urls','config'), namespace='config')),   
    path('administrar/',include(('aplicaciones.admon.urls','admon'), namespace='admon')),   
    path('geografico/', include(('aplicaciones.geografico.urls', 'geografico'), namespace='geografico')),
    path('catedratico/', include(('aplicaciones.catedratico.urls', 'catedratico'), namespace='catedratico')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplicaciones/geografico/models.py
from django.db import models

from crum import get_current_user
from aplicaciones.config.models import AuditModel
from aplicaciones.config.choices import GENDER_CHOICES
# Create your models here.

class Pais(AuditModel):
    """Model definition for MODELNAME."""

    # TODO: Define fields here
    nombre = models.CharField(max_length=100)

    class Meta:
        """Meta definition for MODELNAME."""

        verbose_name = 'Pais'
        verbose_name_plural = 'Paises'

    def __str__(self):
        """Unicode representation of MODELNAME."""
        return self.nombre
    
    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.user_create = user
        else:
            self.user_modified = user

        self.nombre = self.nombre.upper()       
        super(Pais, self).save(*args, **kwargs)
    
class Departamento(AuditModel):
    """Model definition for MODELNAME."""

    # TODO: Define fields here
    nombre = models.CharField(max_length=100)
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE, related_name='departamento')
    

    class Meta:
        """Meta definition for MODELNAME."""

        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'

    def __str__(self):
        """Unicode representation of MODELNAME."""
        return self.nombre
    
    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.user_create = user
        else:
            self.user_modified = user

        self.nombre = self.nombre.upper()
       
        super(Departamento, self).save(*args, **kwargs)


class Ciudad(AuditModel):
    """Model definition for MODELNAME."""

    # TODO: Define fields here
    nombre = models.CharField(max_length=100)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE, related_name='Ciudad')
    

    class Meta:
        """Meta definition for MODELNAME."""

        verbose_name = 'Ciudad'
        verbose_name_plural = 'Ciudades'

    def __str__(self):
        """Unicode representation of MODELNAME."""
        return self.nombre
    
    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.user_create = user
        else:
            self.user_modified = user

        self.nombre = self.nombre.upper()
       
        super(Ciudad, self).save(*args, **kwargs)


class Conocimiento(AuditModel):
    """Model definition for Escalafon."""

    # TODO: Define fields here
    descripcion = models.CharField(max_length=100)
   

    class Meta:
        """Meta definition for Escalafon."""

        verbose_name = 'Conocimiento'
        verbose_name_plural = 'Conocimientos'

    def __str__(self):
        """Unicode representation of Escalafon."""
        return self.descripcion

    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.user_create = user
        else:
            self.user_modified = user
        self.descripcion = self.descripcion.upper()       
        super(Conocimiento, self).save(*args, **kwargs)

class Formacion(AuditModel):
    """Model definition for Escalafon."""

    # TODO: Define fields here
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=100)
   

    class Meta:
        """Meta definition for Escalafon."""

        verbose_name = 'Formacion'
        verbose_name_plural = 'Formaciones'

    def __str__(self):
        """Unicode representation of Escalafon."""
        return self.nombre

    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.user_create = user
        else:
            self.user_modified = user

        self.nombre = self.nombre.upper()
        self.descripcion = self.descripcion.upper()       
        super(Formacion, self).save(*args, **kwargs)

aplicaciones/geografico/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.http import HttpResponseRedirect, JsonResponse

from django.contrib.auth.decorators import login_required, permission_required

from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from aplicaciones.config.views import SinPrivilegios, ValidatePermissionRequiredMixin


from .models import Pais, Departamento, Ciudad, Conocimiento, Formacion
from .forms import  PaisForm, DepartamentoForm, CiudadForm, ConocimientoForm, FormacionForm

class PaisListView(SinPrivilegios, ValidatePermissionRequiredMixin, SuccessMessageMixin, ListView):
    permission_required = 'geografico.view_pais'
    model = Pais
    template_name = "pais/read.html"
    error_message = "Error al actualizar el registro, verifique los Campos."
    context_object_name = "obj"   
   
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Datos del Pais'
        context['create_url'] = reverse_lazy('geografico:pais_new')
        context['list_url'] = reverse_lazy('geografico:pais_list')
        context['entity'] = 'Pais'
        #context['edad'] = Paciente.objects.get_edad()
        return context


class PaisNew(SuccessMessageMixin, SinPrivilegios, CreateView):
    permission_required = "add_pais"
    model = Pais
    template_name = "pais/add.html"
    context_object_name = "obj"
    form_class = PaisForm
    success_url = reverse_lazy("geografico:pais_list")
   
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Registro de pais'
        context['entity'] = 'Pais_Crear'
        context['list_url'] = reverse_lazy("geografico:pais_list")
        context['action'] = 'add'
        return context


class PaisEdit(SuccessMessageMixin, SinPrivilegios, ValidatePermissionRequiredMixin, UpdateView):
    permission_required = "change_pais"
    model = Pais
    template_name = "pais/add.html"
    context_object_name = "obj"
    form_class = PaisForm
    success_url = reverse_lazy("geografico:pais_list")
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Actualizar Datos'
        context['entity'] = 'Pais'
        context['list_url'] = self.success_url
        context['action'] = 'edit'
        #context['edad'] = self.get_edad()
        
        return context


@login_required(login_url='/login/')
@permission_required('geografico.change_pais', login_url='/login/')
def pais_inactivar(request, id):
    pais = Pais.objects.filter(pk=id).first()

    if request.method=='POST':
        if pais:
            pais.state= not pais.state
            pais.save()
            return HttpResponse("OK")
        return HttpResponse("FAIL")    
    return HttpResponse("FAIL")
    

class DepartamentoListView(SinPrivilegios, ValidatePermissionRequiredMixin, SuccessMessageMixin, ListView):
    permission_required = 'geografico.view_departamento'
    model = Departamento
    template_name = "departamento/read.html"
    error_message = "Error al actualizar el registro, verifique los Campos."
    context_object_name = "obj"   
   
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Datos del departamento'
        context['create_url'] = reverse_lazy('geografico:depto_new')
        context['list_url'] = reverse_lazy('geografico:depto_list')
        context['entity'] = 'Departamento'
        
        return context


class DepartamentoNew(SuccessMessageMixin, SinPrivilegios, CreateView):
    permission_required = "add_departamento"
    model = Departamento
    template_name = "departamento/add.html"
    context_object_name = "obj"
    form_class = DepartamentoForm
    success_url = reverse_lazy("geografico:depto_list")
   
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Registro de departamento'
        context['entity'] = 'Departamento_Crear'
        context['list_url'] = reverse_lazy("geografico:depto_list")
        context['action'] = 'add'
        return context


class DepartamentoEdit(SuccessMessageMixin, SinPrivilegios, ValidatePermissionRequiredMixin, UpdateView):
    permission_required = "change_departamento"
    model = Departamento
    template_name = "departamento/add.html"
    context_object_name = "obj"
    form_class = DepartamentoForm
    success_url = reverse_lazy("geografico:depto_list")
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Actualizar Datos'
        context['entity'] = 'Departamento'
        context['list_url'] = self.success_url
        context['action'] = 'edit'
        #context['edad'] = self.get_edad()
        
        return context


@login_required(login_url='/login/')
@permission_required('geografico.change_departamento', login_url='/login/')
def depto_inactivar(request, id):
    departamento = Departamento.objects.filter(pk=id).first()

    if request.method=='POST':
        if departamento:
            departamento.state= not departamento.state
            departamento.save()
            return HttpResponse("OK")
        return HttpResponse("FAIL")    
    return HttpResponse("FAIL")


class CiudadListView(SinPrivilegios, ValidatePermissionRequiredMixin, SuccessMessageMixin, ListView):
    permission_required = 'geografico.view_ciudad'
    model = Ciudad
    template_name = "ciudad/read.html"
    error_message = "Error al actualizar el registro, verifique los Campos."
    context_object_name = "obj"   
   
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Datos del departamento'
        context['create_url'] = reverse_lazy('geografico:ciudad_new')
        context['list_url'] = reverse_lazy('geografico:ciudad_list')
        context['entity'] = 'Ciudad'
        
        return context


class CiudadNew(SuccessMessageMixin, SinPrivilegios, CreateView):
    permission_required = "add_ciudad"
    model = Ciudad
    template_name = "ciudad/add.html"
    context_object_name = "obj"
    form_class = CiudadForm
    success_url = reverse_lazy("geografico:ciudad_list")
   
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Registro de Ciudad'
        context['entity'] = 'Ciudad_Crear'
        context['list_url'] = reverse_lazy("geografico:ciudad_list")
        context['action'] = 'add'
        return context


class CiudadEdit(SuccessMessageMixin, SinPrivilegios, ValidatePermissionRequiredMixin, UpdateView):
    permission_required = "change_ciudad"
    model = Ciudad
    template_name = "departamento/add.html"
    context_object_name = "obj"
    form_class = CiudadForm
    success_url = reverse_lazy("geografico:ciudad_list")
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()

aplicaciones/geografico/templates/pais/add.html
{% extends 'cruds/form.html' %}

aplicaciones/geografico/templates/pais/del.html
{% extends 'esquema/body.html' %}

{% block content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">¿Eliminar {{ obj.nombre }}?</div>
                <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i>Si, Eliminar</button>
                
                <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
              </div>
              <div class="col-auto">
                <i class="far fa-question-circle fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
</form>
{% endblock %}

aplicaciones/geografico/templates/pais/inactivar.html
<div class="modal-dialog modal-sm">
    <div class="modal-content">
        <form method="POST" class="form-inline">
            {% csrf_token %}
            <div class="col">
                <div class="card border-left-danger shadow h-100 py-2">
                  <div class="card-body">
                    <div class="row no-gutters align-items-center">
                      <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase">
                            <div class="alert">
                                ¿ Inactivar <b>{{ obj.nombre }} </b> ?
                            </div>
                        </div>
                      </div>
                      <div class="row">
                        <button type="button" class="btn btn-danger" id="btnInactivar"><i class="far fa-question-circle"></i>Si, Inactivar</button>
                        <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                            No, Cancelar
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
        </form>
    </div>
  </div>
  
  <script>
  $(document).ready(function(){
  
    var token = $('input[name=csrfmiddlewaretoken]').val();
    $.ajaxSetup({
          beforeSend: function(xhr, settings) {
              if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                  xhr.setRequestHeader("X-CSRFToken", token);
              }
          }
      });
  
    $("#btnInactivar").click(function(e){
        e.preventDefault();
        //alert("Probando");
  
        var id = {{ obj.id }};
        var template="{% url 'clinica:paciente_inactivar' obj.id %}";
        //template += id;
        var data = {"id":id};
        data = JSON.stringify(data);
  
        $.ajax({
          type: "POST",
          url: template,
          data: data,
          beforeSend: function(xhr,settings){
            $.ajaxSettings.beforeSend(xhr,settings);
          },
          success: function(response){
            console.log(response);
            cerrar_modal();
            alert(response);
            var tipo=(response.startsWith('Paciente no existe') ? 'red':'green' );
            mensaje(response,tipo);
          },
          error: function(jqXHR, textStatus, errorThrow){
            console.log(textStatus, errorThrow);
            mensaje(errorThrow,'red');
            cerrar_modal();
          }
        });
    });
  
  });
  </script>

aplicaciones/geografico/templates/pais/read.html
{% extends 'cruds/list.html' %}

{% block table_head %}
<th style="text-align: center;">ID</th>

<th style="text-align: center;">Nombre</th>
<th style="text-align: center;">Activo / Inactivo</th>
<th style="text-align: center;">Acciones</th>

{% endblock table_head %}

{% block table_body %}
<td style="text-align: center;">{{ e.id }}</td>

<td>{{ e.nombre}}</td>

<td style="text-align: center;">
  <div onclick="inactivar({{e.id}})">
    {% if e.state %}
    <button class="btn btn-outline-info btn-circle btn-xs">
      <i class="far fa-thumbs-up text-primary"></i>
    </button>
    {% else %}
    <button class="btn btn-outline-danger btn-circle btn-xs">
      <i class="far fa-thumbs-down text-danger"></i>
    </button>
    {% endif %}
  </div>
</td>

<td style="text-align: center;">
  {% if e.state %}
    <a href="{% url 'geografico:pais_edit' e.id %}" class="btn btn-warning btn-circle btn-xs" role="button"><i
      class="far fa-edit"> </i></a>    

  {% else %}
    <a href="#" class="btn btn-danger btn-circle btn-xs" role="button"><i class="fa fa-user-times" aria-hidden="true"></i></a>
  {% endif %}
</td>
{% endblock table_body %}

{% block js_page %}
<script>
  function inactivar(id)
  {
    var data = {id:id};
    data = JSON.stringify(data);
    var token = '{{csrf_token}}';
    
    $.ajax({
      headers : {"X-CSRFToken": token},
      type:"POST",
      url:"/geografico/pais/inactivar/"+id,
      data: data,
      success: function(response){
        if(response==="OK")
        {
          location.reload(true);
        }
        else{
          mensaje("Error Intentado Cambiar Estado");
        }
      },
      error: function(jqXHR, textStatus, errorThrow){
        console.log(textStatus, errorThrow);
        mensaje(errorThrow,'red');
        cerrar_modal();
      }
    });
  }

</script>
{% endblock %}