aplicaciones/admon/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    #usuarios
    path('usuario/list/',UserListView.as_view(), name='user_list'),
    path('usuario/new/',UserCreateView.as_view(), name='user_new'),
    path('usuario/edit/<int:pk>',UserEditView.as_view(), name='user_edit'),
    path('usuario/del/<int:pk>',UsuarioDeleteView.as_view(), name='user_del'),
    path('usuario/ver/<int:pk>',UserDetalleView.as_view(), name='user_ver'),   
    path('profile/', UserPerfilView.as_view(), name='user_profile'),
    
    path('usuario/change/password/', PasswordChangeView.as_view(), name='user_change_pass'),
]

aplicaciones/geografico/urls.py
from django.urls import path
from .views import *

urlpatterns = [    
    path('pais/list/', PaisListView.as_view(), name='pais_list'),
    path('pais/alta/', PaisNew.as_view(), name='pais_new'),
    path('pais/update/<int:pk>', PaisEdit.as_view(), name='pais_edit'),
    path('pais/inactivar/<int:id>', pais_inactivar, name='pais_inactivar'),

    path('depto/list/', DepartamentoListView.as_view(), name='depto_list'),
    path('depto/alta/', DepartamentoNew.as_view(), name='depto_new'),
    path('depto/update/<int:pk>', DepartamentoEdit.as_view(), name='depto_edit'),
    path('depto/inactivar/<int:id>', depto_inactivar, name='depto_inactivar'),

    path('ciudad/list/', CiudadListView.as_view(), name='ciudad_list'),
    path('ciudad/alta/', CiudadNew.as_view(), name='ciudad_new'),
    path('ciudad/update/<int:pk>', CiudadEdit.as_view(), name='ciudad_edit'),
    path('ciudad/inactivar/<int:id>', ciudad_inactivar, name='ciudad_inactivar'),

    path('conocimiento/list/', ConocimientoListView.as_view(), name='cono_list'),
    path('conocimiento/alta/', ConocimientoNew.as_view(), name='cono_new'),
    path('conocimiento/update/<int:pk>', ConocimientoEdit.as_view(), name='cono_edit'),
    path('conocimiento/inactivar/<int:id>', cono_inactivar, name='cono_inactivar'),

    path('formacion/list/', FormacionListView.as_view(), name='form_list'),
    path('formacion/alta/', FormacionNew.as_view(), name='form_new'),
    path('formacion/update/<int:pk>', FormacionEdit.as_view(), name='form_edit'),
    path('formacion/inactivar/<int:id>', form_inactivar, name='form_inactivar'),

]

aplicaciones/home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('dash/', Home.as_view(), name='home'),    
    path('login/',auth_views.LoginView.as_view(template_name='home/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/', MyPasswordChangeView.as_view(), name='pass_change'),
    path('change-password/done/', MyPasswordResetDoneView.as_view(), name='pass_change_done'),
]

universidad/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from universidad import settings



urlpatterns = [
    path('',include(('aplicaciones.home.urls','home'), namespace='home')),
    path('config/',include(('aplicaciones.config.urls','config'), namespace='config')),   
    path('administrar/',include(('aplicaciones.admon.urls','admon'), namespace='admon')),   
    path('geografico/', include(('aplicaciones.geografico.urls', 'geografico'), namespace='geografico')),
    path('catedratico/', include(('aplicaciones.catedratico.urls', 'catedratico'), namespace='catedratico')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/esquema/body.html
{% extends 'esquema/index.html' %}
{% load static %}
{% block head %}

{% endblock head %}
{% block body %}

<body class="hold-transition sidebar-mini">
  <!-- Site wrapper -->
  <div class="wrapper">
    <!-- Navbar HEADER-->
    {% block header %}
    {% include 'esquema/header.html' %}
    {% endblock header %}
    <!-- /.navbar -->
    <!-- Main Sidebar Container -->
    {% block sidebar %}
    {% include 'esquema/sidebar.html' %}
    {% endblock sidebar %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header badge-info">
        <div class="container-fluid">
          <div class="row mb-0 m-0 p-0">
            {% block bienvenida %}
            
            {% endblock bienvenida %}
            {% block link %}
            
            {% endblock link %}
          </div>
        </div><!-- /.container-fluid -->
      </section>

      <!-- Main content -->
      <section class="content">
        {% block content %}
        {% endblock content %}
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    {% block footer %}
    {% include 'esquema/footer.html' %}
    {% endblock footer %}

    {% block control-sidebar %}
      {% include 'esquema/control-sidebar.html' %}
    {% endblock control-sidebar %}
   
  </div>
  <!-- ./wrapper -->
  <script>
    {% if messages %}
      var html = '<p>';
      {% for message in messages %}
        html += '{{ message }}<br>';
      {% endfor %}
      html += '</p>';
      Swal.fire({
        title: 'info!',
        html: html,
        icon: 'info'
      });
    {% endif %}

  </script>
  
  {% block js_page %}
    
  {% endblock js_page %}
    
</body>
{% endblock %}

templates/esquema/control-sidebar.html
{% load static %}
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-light mt-2">
   <section class="container">
       <div class="container-fluid">
           <div class="row mt-2"> <a href="{% url 'admon:user_profile' %}">Perfil</a>  </div>
           <div class="row mt-2"> <a href=" {% url 'home:pass_change' %}"> Cambiar Constraseña</a>  </div>
           <div class="row mt-2"> <a href=" {% url 'home:logout' %} "> Salir del sistema</a> </div>            
           <div class="row mt-2"> 
               <a class="dropdown-item bg-gray" style="color: white; font-size: 12px;" href="#">
                   Sú último acceso fue <br> {{ request.user.last_login }}    
               </a>
           </div>
           <div class="row"></div>
       </div>
   </section>
</aside>
 <!-- /.control-sidebar -->

templates/esquema/footer.html
<footer class="main-footer">
  <!-- To the right -->
  <div class="float-right d-none d-sm-inline">
      Mas que servcios
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2023-2024 <a href="https://adminlte.io">samanaj</a>.</strong> All rights reserved.
</footer>

templates/esquema/header.html
{% load static %}
<nav class="main-header navbar navbar-expand navbar-primary navbar-dark">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="{% url 'home:home' %}" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Contacto</a>
    </li>
  </ul>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Navbar Search -->
    <li class="nav-item">
      <a class="nav-link" data-widget="navbar-search" href="#" role="button">
        <i class="fas fa-search"></i>
      </a>
      <div class="navbar-search-block">
        <form class="form-inline">
          <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
              <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
              </button>
              <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                <i class="fas fa-times"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>

    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-comments"></i>
        <span class="badge badge-danger navbar-badge">3</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="{% static 'img/user1-128x128.jpg' %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Brad Diesel
                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">Call me whenever you can...</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="{% static 'img/user8-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                John Pierce
                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">I got your message bro</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="{% static 'img/user3-128x128.jpg' %} " alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Nora Silvester
                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">The subject goes here</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
      </div>
    </li>
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header">15 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i> 4 new messages
          <span class="float-right text-muted text-sm">3 mins</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-users mr-2"></i> 8 friend requests
          <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-file mr-2"></i> 3 new reports
          <span class="float-right text-muted text-sm">2 days</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="fullscreen" href="#" role="button">
        <i class="fas fa-expand-arrows-alt"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">        
        <i class="fas fa-th-large"></i>        
      </a>      
    </li>
  </ul>
</nav>

templates/esquema/index.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {{ title }}</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %} ">
    <!-- sweetalert2 -->
    <link rel="stylesheet" href="{% static 'plugins/sweetalert2/sweetalert2.min.css' %}">
    <!-- jquery-confirm -->
    <link rel="stylesheet" href="{% static 'css/jquery-confirm.min.css' %}">
    <!-- jquery-ui css -->
    <link rel="stylesheet" href="{% static 'plugins/jquery-ui/jquery-ui.min.css' %}">

    <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'css/adminlte.min.css' %} ">
    
    {% block extra_css %}
       
    {% endblock extra_css %}
        
    
    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- jquery ui -->
    <script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"> </script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
    <!-- sweetalert2 -->
    <script src="{% static 'plugins/sweetalert2/sweetalert2.all.min.js' %}"></script>
    <!-- jaquery confirm -->
    <script src="{% static 'js/jquery-confirm.min.js'%}"> </script>
    <!-- propia -->
    <script src="{% static 'js/mensaje.js'%}"> </script>

    <script src="{% static 'js/adminlte.min.js'%}"> </script>
    <!-- AdminLTE App -->
    <script src="{% static 'plugins/toastr/toastr.min.js'%}"> </script>
    
    {% block extra_js %}
        
    {% endblock extra_js %}
    
    {% block extra_head %}
        
    {% endblock extra_head %}

</head>

{% block body %}
    
{% endblock body %}
    
</html>

templates/esquema/index2.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario Responsivo</title>

    <!-- Agregar los estilos de Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
</head>
<body>

    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h3>Columna 1</h3>
                <form>
                    <div class="mb-3">
                      <label for="nombre" class="form-label">Nombre</label>
                      <input type="text" class="form-control" id="nombre">
                    </div>
                    <div class="mb-3">
                      <label for="email" class="form-label">Email</label>
                      <input type="email" class="form-control" id="email">
                    </div>
                </form>           
            </div>
            
            <div class="col">
                <h3>Columna 2</h3>
                <form>
                    <div class="mb-3">
                      <label for="telefono" class="form-label">Teléfono</label>
                      <input type="text" class="form-control" id="telefono">
                    </div>
                </form>           
            </div>
            
            <div class="col">
                <h3>Columna 3</h3>
                <form>
                    <div class="mb-3">
                      <label for="ciudad" class="form-label">Ciudad</label>
                      <select class="form-select" id="ciudad">
                        <option value="">Selecciona una ciudad</option>
                        <option value="madrid">Madrid</option>
                        <option value="barcelona">Barcelona</option>
                        <option value="valencia">Valencia</option>
                      </select>
                    </div>
                </form>           
            </div>
            
            <div class="col">
                <h3>Columna 4</h3>
                <form>
                    <div class="mb-3">
                      <label for="mensaje" class="form-label">Mensaje</label>
                      <textarea class="form-control" id="mensaje" rows="3"></textarea>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </form>            
            </div>
        </div>
    </div>
    
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/esquema/sidebar.html
{% load static %}
<aside class="main-sidebar bg-light-primary  elevation-4">
  <!-- Brand Logo -->
  <a href="{% url 'home:home' %}" class="brand-link">
    <img src="{% static 'img/AdminLTELogo.png'%}"  alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8"> 
    <span class="brand-text font-weight-light">UNIVERSIDAD </span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <td></td>
      <div class="image">
        <img src="{% static 'img/user2-160x160.jpg'%}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">{{ user }}</a>
      </div>
    </div>

    <!-- SidebarSearch Form -->
    <!-- <div class="form-inline">
      <div class="input-group" data-widget="sidebar-search">
        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-sidebar">
            <i class="fas fa-search fa-fw"></i>
          </button>
        </div>
      </div>
    </div> -->

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->   
            
        <li class="nav-item bg-gray-light">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-copy"></i>
            <p>
              Administración
              <i class="fas fa-angle-left right"></i>              
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'admon:user_list' %}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p">Usuarios</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item bg-gray-light">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-chart-pie"></i>
            <p>
              Gestión de Catalogos
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'geografico:pais_list' %}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Pais</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'geografico:depto_list' %}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Eepartamento</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'geografico:ciudad_list' %}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Ciudad</p>
              </a>
            </li>

            <li class="nav-item">
              <a href="{% url 'geografico:cono_list' %}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Conocimientos</p>
              </a>
            </li>

            <li class="nav-item">
              <a href="{% url 'geografico:form_list' %}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Formacion</p>
              </a>
            </li>
            
          </ul>
        </li>
        <li class="nav-item bg-gray-light">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-tree"></i>
            <p>
              Gestión de Citas
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <!-- <a href=" #" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Citas</p>
              </a> -->
            </li>
            <li class="nav-item">
              <a href="# " class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Calendario</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="../UI/buttons.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Buttons</p>
              </a>
            </li>
            
          </ul>
        </li>
        <li class="nav-item bg-gray-light">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-edit"></i>
            <p>
              Forms
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="../forms/general.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>General Elements</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="../forms/advanced.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Advanced Elements</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item bg-gray-light">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-table"></i>
            <p>
              Tables
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="../tables/simple.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Simple Tables</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="../tables/data.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>DataTables</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="../tables/jsgrid.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>jsGrid</p>
              </a>
            </li>
          </ul>
        </li>
        
        <li class="nav-item menu-open bg-gray-light">
          <a href="#" class="nav-link active bg-warning">
            <i class="nav-icon far fa-plus-square"></i>
            <p>
              Extras
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>
                  Login & Register v1
                  <i class="fas fa-angle-left right"></i>
                </p>
              </a>
              <ul class="nav nav-treeview bg-dark">
                <li class="nav-item">
                  <a href="../examples/login.html" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Login v1</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="../examples/register.html" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Register v1</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="../examples/forgot-password.html" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Forgot Password v1</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="../examples/recover-password.html" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Recover Password v1</p>
                  </a>
                </li>
              </ul>
            </li>
            <li class="nav-item bg-gray-light">
              <a href="#" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>
                  Login & Register v2
                  <i class="fas fa-angle-left right"></i>
                </p>
              </a>
              <ul class="nav nav-treeview bg-dark">
                <li class="nav-item">
                  <a href="../examples/login-v2.html" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Login v2</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="../examples/register-v2.html" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Register v2</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="../examples/forgot-password-v2.html" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Forgot Password v2</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="../examples/recover-password-v2.html" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Recover Password v2</p>
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </li>
        
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->

  

</aside>